language: node_js
sudo: false

node_js:
  - "0.12"
  - "4"
  - "6"
  - "7"

before_script:
  - wget https://github.com/nats-io/nats-streaming-server/releases/download/v0.2.2/nats-streaming-server-linux-amd64.zip -O nats-streaming-server-amd64.zip
  - unzip nats-streaming-server-amd64.zip
  - mv nats-streaming-server-linux-amd64 nats-streaming-server

after_success:
  - npm run coveralls
