language: node_js
sudo: false

node_js:
  - "4"
  - "6"
  - "8"
  - "9"

git:
  depth: false

env:
  - STAN_VERSION=v0.8.0-beta

before_script:
  - wget "https://github.com/nats-io/nats-streaming-server/releases/download/$STAN_VERSION/nats-streaming-server-$STAN_VERSION-linux-amd64.zip" -O tmp.zip
  - unzip tmp.zip
  - mv "nats-streaming-server-$STAN_VERSION-linux-amd64" nats-streaming-server
  - mkdir nats-streaming-server/logs


script:
  - if [[ "$TRAVIS_NODE_VERSION" == 4 ]]; then npm test; fi
  - if [[ "$TRAVIS_NODE_VERSION" == 6 ]]; then npm test; fi
  - if [[ "$TRAVIS_NODE_VERSION" == 8 ]]; then npm test; fi
  - if [[ "$TRAVIS_NODE_VERSION" == 9 ]]; then npm run coveralls; fi

after_failure:
  - cat nats-streaming-server/logs/*.log